spring.application.name=loginbackend

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=Qwerty123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true